name: Tikal
markdown: redcarpet
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
cats:
 - name: alm
   displayName: ALM
   styleClass: "first leaf menu-mlid-685 alm"
   imageurl: alm.jpg        
 - name: java
   displayName: Java
   styleClass: "leaf menu-mlid-686 java"
   imageurl: java.jpg
 - name: js
   displayName: JS
   styleClass: "leaf menu-mlid-687 js"
   imageurl: js.jpg
 - name: net
   displayName: .NET
   styleClass: "leaf menu-mlid-688 .net"
   imageurl: net.jpg
 - name: ror
   displayName: RoR
   styleClass: "last leaf menu-mlid-689 ror"
   imageurl: ror.jpg
